export type QuestionType = "single" | "input" | "order";

export type Question = {
  id: string;
  grade: "七年级" | "八年级";
  semester: "上册" | "下册";
  chapter: string;
  domain: string;
  point: string;
  difficulty: "基础" | "中档" | "综合";
  type: QuestionType;
  stem: string;
  options?: string[];
  answer: string | string[];
  unit?: string;
  diagram?:
    | "numberline"
    | "angles"
    | "parallel"
    | "coordinate"
    | "triangle"
    | "congruence"
    | "bisector"
    | "symmetry"
    | "pythagorean"
    | "parallelogram"
    | "line"
    | "bars";
  hint: string;
  steps: string[];
  errorTags: string[];
  sourceNote: string;
  weight: number;
};

export const domains = [
  "数与式",
  "方程与不等式",
  "几何基础与坐标",
  "三角形与全等",
  "对称与特殊图形",
  "代数变形",
  "勾股·四边形·函数",
  "统计与数据",
] as const;

const sourceNote = "依据北京中考近三年公开试题结构与官方评析进行题型校准；非官方逐题正确率。";

export const questions: Question[] = [
  {
    id: "q01",
    grade: "七年级",
    semester: "上册",
    chapter: "有理数",
    domain: "数与式",
    point: "有理数减法",
    difficulty: "基础",
    type: "single",
    stem: "计算：−3−(−5) 的结果是（　）。",
    options: ["−8", "−2", "2", "8"],
    answer: "2",
    hint: "把减去一个负数改写成加上它的相反数。",
    steps: ["识别运算：减去 −5。", "利用法则：−3−(−5)=−3+5。", "在数轴上从 −3 向右移动5格，得到2。"],
    errorTags: ["符号法则", "负数运算"],
    sourceNote,
    weight: 1,
  },
  {
    id: "q02",
    grade: "七年级",
    semester: "上册",
    chapter: "有理数",
    domain: "数与式",
    point: "数轴与绝对值",
    difficulty: "基础",
    type: "input",
    stem: "数轴上点A表示−2，点B表示4，则线段AB的长度为多少？",
    answer: "6",
    unit: "个单位长度",
    diagram: "numberline",
    hint: "两点间的距离等于它们所表示数的差的绝对值。",
    steps: ["读图得到 A=−2，B=4。", "写出距离：AB=|4−(−2)|。", "计算得 AB=|6|=6。"],
    errorTags: ["绝对值", "数轴距离"],
    sourceNote,
    weight: 1,
  },
  {
    id: "q03",
    grade: "七年级",
    semester: "上册",
    chapter: "整式的加减",
    domain: "数与式",
    point: "去括号与合并同类项",
    difficulty: "基础",
    type: "single",
    stem: "化简 3a−2(a−4)，正确结果是（　）。",
    options: ["a−8", "a+8", "5a−8", "5a+8"],
    answer: "a+8",
    hint: "括号前是−2，去括号时括号内每一项都要乘−2。",
    steps: ["分配 −2：−2(a−4)=−2a+8。", "原式变为 3a−2a+8。", "合并同类项，得到 a+8。"],
    errorTags: ["去括号", "合并同类项"],
    sourceNote,
    weight: 1,
  },
  {
    id: "q04",
    grade: "七年级",
    semester: "下册",
    chapter: "实数",
    domain: "数与式",
    point: "平方根与立方根",
    difficulty: "基础",
    type: "single",
    stem: "计算 √9+∛(−8)，结果是（　）。",
    options: ["−5", "−1", "1", "5"],
    answer: "1",
    hint: "先分别求9的算术平方根和−8的立方根。",
    steps: ["√9 表示9的算术平方根，所以 √9=3。", "因为 (−2)³=−8，所以 ∛(−8)=−2。", "相加得到 3+(−2)=1。"],
    errorTags: ["算术平方根", "立方根"],
    sourceNote,
    weight: 1,
  },
  {
    id: "q05",
    grade: "七年级",
    semester: "上册",
    chapter: "一元一次方程",
    domain: "方程与不等式",
    point: "解一元一次方程",
    difficulty: "基础",
    type: "input",
    stem: "解方程 3(x−2)=2x+5，x=____。",
    answer: "11",
    hint: "先去括号，再把含x的项移到同一边。",
    steps: ["去括号：3x−6=2x+5。", "移项：3x−2x=5+6。", "合并，得到 x=11，并可代回检验。"],
    errorTags: ["去括号", "移项", "方程检验"],
    sourceNote,
    weight: 1.1,
  },
  {
    id: "q06",
    grade: "七年级",
    semester: "下册",
    chapter: "二元一次方程组",
    domain: "方程与不等式",
    point: "加减消元",
    difficulty: "中档",
    type: "single",
    stem: "方程组 x+y=7，x−y=1 的解为（　）。",
    options: ["x=3，y=4", "x=4，y=3", "x=6，y=1", "x=1，y=6"],
    answer: "x=4，y=3",
    hint: "把两个方程相加，可以直接消去y。",
    steps: ["两式相加：2x=8。", "解得 x=4。", "代入 x+y=7，得到 y=3。"],
    errorTags: ["加减消元", "回代"],
    sourceNote,
    weight: 1.2,
  },
  {
    id: "q07",
    grade: "七年级",
    semester: "下册",
    chapter: "不等式与不等式组",
    domain: "方程与不等式",
    point: "解一元一次不等式",
    difficulty: "基础",
    type: "single",
    stem: "不等式 2x−3<5 的解集是（　）。",
    options: ["x<1", "x<4", "x>1", "x>4"],
    answer: "x<4",
    hint: "先移项，再把不等式两边同时除以正数2。",
    steps: ["两边同时加3：2x<8。", "两边同时除以正数2，不等号方向不变。", "得到 x<4。"],
    errorTags: ["不等式方向", "移项"],
    sourceNote,
    weight: 1,
  },
  {
    id: "q08",
    grade: "七年级",
    semester: "下册",
    chapter: "相交线与平行线",
    domain: "几何基础与坐标",
    point: "平行线的性质",
    difficulty: "基础",
    type: "input",
    stem: "如图，直线a∥b，∠1=65°，∠2与∠1是内错角，则∠2=____°。",
    answer: "65",
    unit: "°",
    diagram: "parallel",
    hint: "两直线平行时，内错角相等。",
    steps: ["从题目识别已知条件 a∥b。", "定位∠1和∠2，它们是一对内错角。", "利用两直线平行，内错角相等，得∠2=65°。"],
    errorTags: ["角的位置关系", "平行线性质"],
    sourceNote,
    weight: 1.1,
  },
  {
    id: "q09",
    grade: "七年级",
    semester: "下册",
    chapter: "平面直角坐标系",
    domain: "几何基础与坐标",
    point: "点的平移",
    difficulty: "中档",
    type: "single",
    stem: "点P(−2，3)向右平移5个单位、再向下平移4个单位，所得点P′的坐标是（　）。",
    options: ["(3，−1)", "(−7，−1)", "(3，7)", "(−7，7)"],
    answer: "(3，−1)",
    diagram: "coordinate",
    hint: "向右改变横坐标，向下改变纵坐标。",
    steps: ["向右5个单位：横坐标 −2+5=3。", "向下4个单位：纵坐标 3−4=−1。", "所以 P′=(3，−1)。"],
    errorTags: ["坐标变化", "平移方向"],
    sourceNote,
    weight: 1.2,
  },
  {
    id: "q10",
    grade: "七年级",
    semester: "上册",
    chapter: "几何图形初步",
    domain: "几何基础与坐标",
    point: "邻补角",
    difficulty: "基础",
    type: "input",
    stem: "如图，射线OC把平角∠AOB分成∠AOC和∠COB。若∠AOC=126°，则∠COB=____°。",
    answer: "54",
    unit: "°",
    diagram: "angles",
    hint: "平角等于180°，两个邻补角的和是180°。",
    steps: ["识别∠AOB是平角，所以∠AOB=180°。", "建立关系：∠AOC+∠COB=180°。", "计算∠COB=180°−126°=54°。"],
    errorTags: ["平角", "角度计算"],
    sourceNote,
    weight: 1,
  },
  {
    id: "q11",
    grade: "八年级",
    semester: "上册",
    chapter: "三角形",
    domain: "三角形与全等",
    point: "三角形三边关系",
    difficulty: "中档",
    type: "input",
    stem: "一个三角形的两边长分别为4和7，第三边长x为正整数。x共有多少种可能取值？",
    answer: "7",
    unit: "种",
    diagram: "triangle",
    hint: "第三边必须大于两边之差、小于两边之和。",
    steps: ["由三角形三边关系得 |7−4|<x<7+4。", "化简为 3<x<11。", "正整数x为4、5、6、7、8、9、10，共7种。"],
    errorTags: ["三边关系", "整数解"],
    sourceNote,
    weight: 1.3,
  },
  {
    id: "q12",
    grade: "八年级",
    semester: "上册",
    chapter: "三角形",
    domain: "三角形与全等",
    point: "三角形内角和",
    difficulty: "基础",
    type: "input",
    stem: "三角形的两个内角分别为48°和67°，第三个内角为____°。",
    answer: "65",
    unit: "°",
    diagram: "triangle",
    hint: "三角形三个内角的和等于180°。",
    steps: ["写出内角和关系：48°+67°+x=180°。", "先算48°+67°=115°。", "得到 x=180°−115°=65°。"],
    errorTags: ["内角和", "角度计算"],
    sourceNote,
    weight: 1,
  },
  {
    id: "q13",
    grade: "八年级",
    semester: "上册",
    chapter: "全等三角形",
    domain: "三角形与全等",
    point: "SAS判定",
    difficulty: "中档",
    type: "single",
    stem: "如图，已知AB=DE，AC=DF。要用“SAS”证明△ABC≌△DEF，还需要的条件是（　）。",
    options: ["∠B=∠E", "∠C=∠F", "∠A=∠D", "BC=EF"],
    answer: "∠A=∠D",
    diagram: "congruence",
    hint: "SAS中的角必须是两条已知对应边的夹角。",
    steps: ["已知对应边为 AB↔DE、AC↔DF。", "这两组边的夹角分别是∠A和∠D。", "补充∠A=∠D，可用SAS判定两三角形全等。"],
    errorTags: ["夹角识别", "全等判定"],
    sourceNote,
    weight: 1.4,
  },
  {
    id: "q14",
    grade: "八年级",
    semester: "上册",
    chapter: "全等三角形",
    domain: "三角形与全等",
    point: "角平分线性质",
    difficulty: "中档",
    type: "single",
    stem: "如图，点P在∠AOB的角平分线上，PM⊥OA，PN⊥OB。下列结论正确的是（　）。",
    options: ["PM>PN", "PM<PN", "PM=PN", "无法确定"],
    answer: "PM=PN",
    diagram: "bisector",
    hint: "角平分线上的点到角两边的距离相等。",
    steps: ["确认P位于∠AOB的角平分线上。", "PM、PN分别垂直于角的两边，它们表示点P到两边的距离。", "由角平分线性质得到 PM=PN。"],
    errorTags: ["点到直线距离", "角平分线性质"],
    sourceNote,
    weight: 1.3,
  },
  {
    id: "q15",
    grade: "八年级",
    semester: "上册",
    chapter: "轴对称",
    domain: "对称与特殊图形",
    point: "坐标与轴对称",
    difficulty: "基础",
    type: "single",
    stem: "点A(3，−2)关于y轴的对称点A′的坐标是（　）。",
    options: ["(−3，−2)", "(3，2)", "(−3，2)", "(2，−3)"],
    answer: "(−3，−2)",
    diagram: "symmetry",
    hint: "关于y轴对称时，横坐标互为相反数，纵坐标不变。",
    steps: ["关于y轴对称，点与像到y轴的距离相等。", "横坐标3变为−3。", "纵坐标−2保持不变，得到A′(−3，−2)。"],
    errorTags: ["轴对称", "坐标符号"],
    sourceNote,
    weight: 1.1,
  },
  {
    id: "q16",
    grade: "八年级",
    semester: "上册",
    chapter: "整式的乘法与因式分解",
    domain: "代数变形",
    point: "平方差公式",
    difficulty: "基础",
    type: "single",
    stem: "因式分解 x²−9，结果是（　）。",
    options: ["(x−9)(x+1)", "(x−3)²", "(x−3)(x+3)", "x(x−9)"],
    answer: "(x−3)(x+3)",
    hint: "把9写成3²，识别a²−b²。",
    steps: ["原式是 x²−3²。", "使用平方差公式 a²−b²=(a−b)(a+b)。", "得到 x²−9=(x−3)(x+3)。"],
    errorTags: ["公式识别", "因式分解"],
    sourceNote,
    weight: 1,
  },
  {
    id: "q17",
    grade: "八年级",
    semester: "上册",
    chapter: "分式",
    domain: "代数变形",
    point: "分式方程",
    difficulty: "中档",
    type: "input",
    stem: "解分式方程 2/(x−1)=1，x=____。（需要检验）",
    answer: "3",
    hint: "先写出x≠1，再去分母，最后检验是否为增根。",
    steps: ["确定限制条件：x−1≠0，即x≠1。", "两边同乘x−1，得到2=x−1。", "解得x=3；3≠1且代入原方程成立，所以x=3。"],
    errorTags: ["限制条件", "去分母", "增根检验"],
    sourceNote,
    weight: 1.4,
  },
  {
    id: "q18",
    grade: "八年级",
    semester: "下册",
    chapter: "二次根式",
    domain: "代数变形",
    point: "二次根式化简",
    difficulty: "基础",
    type: "single",
    stem: "化简 √50，正确结果是（　）。",
    options: ["25√2", "10√5", "5√2", "2√5"],
    answer: "5√2",
    hint: "把50分解成一个完全平方数与另一个数的乘积。",
    steps: ["分解被开方数：50=25×2。", "利用√(ab)=√a·√b。", "得到√50=√25·√2=5√2。"],
    errorTags: ["完全平方数", "根式化简"],
    sourceNote,
    weight: 1,
  },
  {
    id: "q19",
    grade: "八年级",
    semester: "下册",
    chapter: "勾股定理",
    domain: "勾股·四边形·函数",
    point: "勾股定理应用",
    difficulty: "基础",
    type: "input",
    stem: "直角三角形的两条直角边长分别为6和8，斜边长为____。",
    answer: "10",
    diagram: "pythagorean",
    hint: "斜边的平方等于两条直角边平方的和。",
    steps: ["设斜边为c，写出 c²=6²+8²。", "计算 c²=36+64=100。", "边长取正值，所以c=10。"],
    errorTags: ["斜边识别", "勾股计算"],
    sourceNote,
    weight: 1.1,
  },
  {
    id: "q20",
    grade: "八年级",
    semester: "下册",
    chapter: "平行四边形",
    domain: "勾股·四边形·函数",
    point: "平行四边形对角线性质",
    difficulty: "基础",
    type: "input",
    stem: "如图，平行四边形ABCD的对角线AC、BD相交于O。若AO=3，则AC=____。",
    answer: "6",
    diagram: "parallelogram",
    hint: "平行四边形的对角线互相平分。",
    steps: ["由平行四边形性质，O是AC的中点。", "因此 AO=OC=3。", "AC=AO+OC=3+3=6。"],
    errorTags: ["对角线性质", "线段关系"],
    sourceNote,
    weight: 1,
  },
  {
    id: "q21",
    grade: "八年级",
    semester: "下册",
    chapter: "一次函数",
    domain: "勾股·四边形·函数",
    point: "待定系数法",
    difficulty: "综合",
    type: "single",
    stem: "一次函数图象经过点(0，−2)和(4，6)，其解析式是（　）。",
    options: ["y=2x−2", "y=−2x+6", "y=x−2", "y=2x+2"],
    answer: "y=2x−2",
    diagram: "line",
    hint: "先由两点求斜率，再利用x=0时的函数值确定截距。",
    steps: ["斜率k=(6−(−2))/(4−0)=8/4=2。", "点(0，−2)说明当x=0时b=−2。", "所以解析式为 y=2x−2。"],
    errorTags: ["斜率", "待定系数法", "函数表达式"],
    sourceNote,
    weight: 1.6,
  },
  {
    id: "q22",
    grade: "八年级",
    semester: "下册",
    chapter: "一次函数",
    domain: "勾股·四边形·函数",
    point: "函数值与图象",
    difficulty: "中档",
    type: "input",
    stem: "函数y=−x+4中，当x=1时，y=____。",
    answer: "3",
    diagram: "line",
    hint: "把x=1代入函数解析式。",
    steps: ["把x=1代入 y=−x+4。", "得到 y=−1+4。", "计算得 y=3；图象上的对应点是(1，3)。"],
    errorTags: ["代入求值", "图象对应"],
    sourceNote,
    weight: 1.1,
  },
  {
    id: "q23",
    grade: "八年级",
    semester: "下册",
    chapter: "数据的分析",
    domain: "统计与数据",
    point: "平均数与中位数",
    difficulty: "基础",
    type: "single",
    stem: "数据2，3，3，6，6的平均数和中位数分别是（　）。",
    options: ["4和3", "4和4", "3和4", "3和3"],
    answer: "4和3",
    diagram: "bars",
    hint: "平均数看总和与个数，中位数看排序后正中间的数。",
    steps: ["总和为2+3+3+6+6=20，共5个数据。", "平均数为20÷5=4。", "数据已排序，中间第3个数是3，所以中位数为3。"],
    errorTags: ["平均数", "中位数"],
    sourceNote,
    weight: 1,
  },
  {
    id: "q24",
    grade: "八年级",
    semester: "下册",
    chapter: "数据的分析",
    domain: "统计与数据",
    point: "加权平均数",
    difficulty: "中档",
    type: "input",
    stem: "某项评价由平时成绩和期末成绩组成，权重分别为30%和70%。若两项成绩分别为80分和90分，则总评为____分。",
    answer: "87",
    unit: "分",
    hint: "分别用成绩乘对应权重，再把两个结果相加。",
    steps: ["写出加权平均：80×30%+90×70%。", "计算得到24+63。", "总评为87分。"],
    errorTags: ["权重", "百分数运算"],
    sourceNote,
    weight: 1.3,
  },
  {
    id: "q25",
    grade: "七年级",
    semester: "下册",
    chapter: "数据的收集、整理与描述",
    domain: "统计与数据",
    point: "抽样调查",
    difficulty: "中档",
    type: "single",
    stem: "为了解全校学生每天的睡眠时间，下列抽样方法中最有代表性的是（　）。",
    options: ["只调查篮球队学生", "只调查初三一个班", "从各年级随机抽取一定数量学生", "在校门口调查最早到校的50人"],
    answer: "从各年级随机抽取一定数量学生",
    hint: "样本既要随机，也要覆盖总体中的不同年级。",
    steps: ["总体是全校学生，包含多个年级和不同作息人群。", "排除只集中于某类学生的便利样本。", "分年级随机抽取能减少偏差，代表性更好。"],
    errorTags: ["样本代表性", "随机抽样"],
    sourceNote,
    weight: 1.2,
  },
  {
    id: "q26",
    grade: "七年级",
    semester: "下册",
    chapter: "数据的收集、整理与描述",
    domain: "统计与数据",
    point: "数据调查流程",
    difficulty: "综合",
    type: "order",
    stem: "请按合理顺序点击下列步骤，完成一次数据调查。",
    options: ["整理并表示数据", "得出结论", "收集数据", "分析数据"],
    answer: ["收集数据", "整理并表示数据", "分析数据", "得出结论"],
    hint: "先获得原始数据，再整理、分析，最后形成结论。",
    steps: ["明确调查问题后，首先按方案收集原始数据。", "将数据分类、列表或画图，形成可读的信息。", "比较、计算并分析数据，最后依据证据得出结论。"],
    errorTags: ["调查流程", "数据分析逻辑"],
    sourceNote,
    weight: 1.4,
  },
];

export const chapterOrder = Array.from(new Set(questions.map((question) => question.chapter)));

